In [163]:
import pandas as pd
import numpy as np

data=pd.read_csv('Train_data.csv')

In [164]:
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,anomaly
3,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [165]:
data.shape

(25192, 42)

In [262]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25192 entries, 0 to 25191
Data columns (total 43 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   protocol_type                25192 non-null  int64
 1   service                      25192 non-null  int64
 2   flag                         25192 non-null  int64
 3   src_bytes                    25192 non-null  int64
 4   dst_bytes                    25192 non-null  int64
 5   land                         25192 non-null  int64
 6   wrong_fragment               25192 non-null  int64
 7   urgent                       25192 non-null  int64
 8   hot                          25192 non-null  int64
 9   num_failed_logins            25192 non-null  int64
 10  logged_in                    25192 non-null  int64
 11  num_compromised              25192 non-null  int64
 12  root_shell                   25192 non-null  int64
 13  su_attempted                 25192 non-null  int64
 14  num_root                     25192 non-null  int64
 15  num_file_creations           25192 non-null  int64
 16  num_shells                   25192 non-null  int64
 17  num_access_files             25192 non-null  int64
 18  num_outbound_cmds            25192 non-null  int64
 19  is_host_login                25192 non-null  int64
 20  is_guest_login               25192 non-null  int64
 21  count                        25192 non-null  int64
 22  srv_count                    25192 non-null  int64
 23  serror_rate                  25192 non-null  float64
 24  srv_serror_rate              25192 non-null  float64
 25  rerror_rate                  25192 non-null  float64
 26  srv_rerror_rate              25192 non-null  float64
 27  same_srv_rate                25192 non-null  float64
 28  diff_srv_rate                25192 non-null  float64
 29  srv_diff_host_rate           25192 non-null  float64
 30  dst_host_count               25192 non-null  int64
 31  dst_host_srv_count           25192 non-null  int64
 32  dst_host_same_srv_rate       25192 non-null  float64
 33  dst_host_diff_srv_rate       25192 non-null  float64
 34  dst_host_same_src_port_rate  25192 non-null  float64
 35  dst_host_srv_diff_host_rate  25192 non-null  float64
 36  dst_host_serror_rate         25192 non-null  float64
 37  dst_host_srv_serror_rate     25192 non-null  float64
 38  dst_host_rerror_rate         25192 non-null  float64
 39  dst_host_srv_rerror_rate     25192 non-null  float64
 40  class                        25192 non-null  object
 41  if_anomaly                   25192 non-null  int64
 42  oc_svm                       25192 non-null  int64
dtypes: float64(15), int64(27), object(1)
memory usage: 8.3+ MB

In [167]:
data.columns

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'class'],
      dtype='object')

In [168]:
data.drop(columns='duration',axis=1,inplace=True)

In [169]:
data.head(3)

,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,tcp,ftp_data,SF,491,0,0,0,0,0,0,...,25,0.17,0.03,0.17,0.0,0.0,0.0,0.05,0.0,normal
1,udp,other,SF,146,0,0,0,0,0,0,...,1,0.00,0.60,0.88,0.0,0.0,0.0,0.00,0.0,normal
2,tcp,private,S0,0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.0,1.0,1.0,0.00,0.0,anomaly

In [170]:
data['protocol_type'].value_counts()

protocol_type
tcp     20526
udp      3011
icmp     1655
Name: count, dtype: int64

In [171]:
data['protocol_type']=data['protocol_type'].map({'tcp':0,'udp':1,'icmp':2})

In [172]:
data.head()

,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,ftp_data,SF,491,0,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,1,other,SF,146,0,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,private,S0,0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,anomaly
3,0,http,SF,232,8153,0,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,http,SF,199,420,0,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [173]:
data['service'].value_counts()

service
http         8003
private      4351
domain_u     1820
smtp         1449
ftp_data     1396
             ...
urh_i           4
pm_dump         3
red_i           3
tim_i           2
http_8001       1
Name: count, Length: 66, dtype: int64

In [174]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
data['service']=le.fit_transform(data['service'])

In [175]:
data.head()

,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,19,SF,491,0,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,1,41,SF,146,0,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,46,S0,0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,anomaly
3,0,22,SF,232,8153,0,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,22,SF,199,420,0,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [176]:
data['flag'].value_counts()

flag
SF        14973
S0         7009
REJ        2216
RSTR        497
RSTO        304
S1           88
SH           43
RSTOS0       21
S2           21
S3           15
OTH           5
Name: count, dtype: int64

In [177]:
data['flag']=LabelEncoder().fit_transform(data['flag'])

In [178]:
data.head()

,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,19,9,491,0,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,1,41,9,146,0,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,46,5,0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,anomaly
3,0,22,9,232,8153,0,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,22,9,199,420,0,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [179]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25192 entries, 0 to 25191
Data columns (total 41 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   protocol_type                25192 non-null  int64
 1   service                      25192 non-null  int64
 2   flag                         25192 non-null  int64
 3   src_bytes                    25192 non-null  int64
 4   dst_bytes                    25192 non-null  int64
 5   land                         25192 non-null  int64
 6   wrong_fragment               25192 non-null  int64
 7   urgent                       25192 non-null  int64
 8   hot                          25192 non-null  int64
 9   num_failed_logins            25192 non-null  int64
 10  logged_in                    25192 non-null  int64
 11  num_compromised              25192 non-null  int64
 12  root_shell                   25192 non-null  int64
 13  su_attempted                 25192 non-null  int64
 14  num_root                     25192 non-null  int64
 15  num_file_creations           25192 non-null  int64
 16  num_shells                   25192 non-null  int64
 17  num_access_files             25192 non-null  int64
 18  num_outbound_cmds            25192 non-null  int64
 19  is_host_login                25192 non-null  int64
 20  is_guest_login               25192 non-null  int64
 21  count                        25192 non-null  int64
 22  srv_count                    25192 non-null  int64
 23  serror_rate                  25192 non-null  float64
 24  srv_serror_rate              25192 non-null  float64
 25  rerror_rate                  25192 non-null  float64
 26  srv_rerror_rate              25192 non-null  float64
 27  same_srv_rate                25192 non-null  float64
 28  diff_srv_rate                25192 non-null  float64
 29  srv_diff_host_rate           25192 non-null  float64
 30  dst_host_count               25192 non-null  int64
 31  dst_host_srv_count           25192 non-null  int64
 32  dst_host_same_srv_rate       25192 non-null  float64
 33  dst_host_diff_srv_rate       25192 non-null  float64
 34  dst_host_same_src_port_rate  25192 non-null  float64
 35  dst_host_srv_diff_host_rate  25192 non-null  float64
 36  dst_host_serror_rate         25192 non-null  float64
 37  dst_host_srv_serror_rate     25192 non-null  float64
 38  dst_host_rerror_rate         25192 non-null  float64
 39  dst_host_srv_rerror_rate     25192 non-null  float64
 40  class                        25192 non-null  object
dtypes: float64(15), int64(25), object(1)
memory usage: 7.9+ MB

In [180]:
X=data.drop('class',axis=1)
y=data['class']

In [253]:
from sklearn.preprocessing import StandardScaler

X_scaled=StandardScaler().fit_transform(X)

In [182]:
y=y.map({'normal':0,'anomaly':1})

In [254]:
y.sample(4)

8879     1
9199     0
23820    1
8741     0
Name: class, dtype: int64

In [227]:
data['class'].value_counts(normalize=True)

class
normal     0.53386
anomaly    0.46614
Name: proportion, dtype: float64

In [255]:
from sklearn.ensemble import IsolationForest

iso_forest=IsolationForest(contamination=0.4661,random_state=42)

In [256]:
data['if_anomaly']=iso_forest.fit_predict(X_scaled)

In [257]:
data.sample(5)

,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,...,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class,if_anomaly,oc_svm
9689,2,13,9,8,0,0,0,0,0,0,...,0.00,1.00,0.25,0.0,0.0,0.0,0.0,anomaly,-1,1
5355,0,22,9,164,9785,0,0,0,0,0,...,0.00,0.01,0.05,0.0,0.0,0.0,0.0,normal,1,0
10567,0,22,9,319,770,0,0,0,0,0,...,0.00,0.02,0.01,0.0,0.0,0.0,0.0,normal,1,0
11599,0,22,9,298,4425,0,0,0,0,0,...,0.00,0.50,0.03,0.0,0.0,0.0,0.0,normal,1,1
958,0,15,1,0,0,0,0,0,0,0,...,0.06,0.00,0.00,0.0,0.0,1.0,1.0,anomaly,-1,1

In [258]:
data['if_anomaly']=data['if_anomaly'].map({1:0,-1:1})

In [259]:
data['if_anomaly']

0        0
1        1
2        0
3        1
4        0
        ..
25187    1
25188    1
25189    1
25190    0
25191    1
Name: if_anomaly, Length: 25192, dtype: int64

In [260]:
from sklearn.metrics import classification_report

print(classification_report(y,data['if_anomaly']))

              precision    recall  f1-score   support

           0       0.68      0.68      0.68     13449
           1       0.64      0.64      0.64     11743

    accuracy                           0.66     25192
   macro avg       0.66      0.66      0.66     25192
weighted avg       0.66      0.66      0.66     25192

In [238]:
#One class SVM
from sklearn.svm import OneClassSVM
 
oc_svm=OneClassSVM(kernel='rbf',gamma='auto',nu=0.4661)

In [242]:
data['oc_svm']=oc_svm.fit_predict(X_scaled)

In [244]:
data['oc_svm']

0        1
1       -1
2        1
3        1
4        1
        ..
25187   -1
25188   -1
25189   -1
25190    1
25191    1
Name: oc_svm, Length: 25192, dtype: int64

In [245]:
data['oc_svm']=data['oc_svm'].map({1:0,-1:1})

In [246]:
print(classification_report(y,data['oc_svm']))

              precision    recall  f1-score   support

           0       0.65      0.65      0.65     13449
           1       0.60      0.60      0.60     11743

    accuracy                           0.63     25192
   macro avg       0.62      0.62      0.62     25192
weighted avg       0.63      0.63      0.63     25192